#IMPORT LIBRARY

In [1]:
import pandas as pd
import numpy as np

#LOAD DATA

In [2]:
sekolah = pd.read_csv('data.csv')
sekolah

,id,bentuk,status,provinsi,guru,siswa_laki_laki,siswa_perempuan,rombongan_belajar,kurikulum,penyelenggaraan,...,jumlah_lab_biologi,jumlah_lab_kimia,jumlah_lab_fisika,jumlah_lab_bahasa,jumlah_lab_ips,jumlah_lab_komputer,perpustakaan_baik,sanitasi_guru_baik,sanitasi_siswa_baik,akreditasi
0,0,SD,N,18,14.0,151.0,170.0,12.0,K-13,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,2
1,1,SD,N,9,25.0,314.0,282.0,20.0,K-13,Double Shift/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,7.0,1
2,2,SD,N,11,9.0,73.0,76.0,6.0,K-13,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,3,SD,S,13,7.0,151.0,113.0,11.0,K-13,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,1
4,4,SMA,S,0,33.0,293.0,381.0,20.0,KTSP,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55581,55581,SMK,S,2,31.0,118.0,198.0,14.0,KTSP,Sehari Penuh/6h,...,0.0,0.0,0.0,0.0,0.0,2.0,1.0,2.0,2.0,1
55582,55582,SD,S,11,11.0,53.0,43.0,6.0,KTSP,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,1
55583,55583,SMK,S,0,11.0,191.0,2.0,11.0,KTSP,Pagi/6h,...,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,2
55584,55584,SMK,S,7,10.0,135.0,82.0,8.0,KTSP,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2
55585,55585,SMK,S,7,6.0,105.0,66.0,7.0,KTSP,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,2

#Mencari Rata Rata Jumlah Atribut yang dimiliki

In [6]:
#filter sekolah by provinsi
sekolahByProvinsi = sekolah.loc[sekolah.provinsi == 11]
sekolahByProvinsi

,id,bentuk,status,provinsi,guru,siswa_laki_laki,siswa_perempuan,rombongan_belajar,kurikulum,penyelenggaraan,...,jumlah_lab_biologi,jumlah_lab_kimia,jumlah_lab_fisika,jumlah_lab_bahasa,jumlah_lab_ips,jumlah_lab_komputer,perpustakaan_baik,sanitasi_guru_baik,sanitasi_siswa_baik,akreditasi
2,2,SD,N,11,9.0,73.0,76.0,6.0,K-13,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
5,5,SD,N,11,8.0,26.0,28.0,6.0,KTSP,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
7,7,SMK,S,11,10.0,99.0,33.0,6.0,KTSP,Pagi/6h,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2
10,10,SMA,S,11,29.0,80.0,272.0,15.0,KTSP,Sehari Penuh/5h,...,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1
13,13,SD,N,11,7.0,86.0,83.0,6.0,K-13,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55561,55561,SD,N,11,10.0,102.0,66.0,6.0,K-13,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
55566,55566,SD,N,11,8.0,42.0,52.0,6.0,KTSP,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2
55569,55569,SD,N,11,8.0,86.0,98.0,6.0,K-13,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
55570,55570,SD,N,11,8.0,98.0,74.0,6.0,K-13,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
55582,55582,SD,S,11,11.0,53.0,43.0,6.0,KTSP,Pagi/6h,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,1

#Lab Sekolah dari Provinsi == 11

In [13]:
params_sekolah = sekolahByProvinsi.iloc[:,36:44].mean()
params_sekolah

jumlah_lab_ipa         0.192544
jumlah_lab_biologi     0.051059
jumlah_lab_kimia       0.045386
jumlah_lab_fisika      0.051754
jumlah_lab_bahasa      0.092162
jumlah_lab_ips         0.010652
jumlah_lab_komputer    0.336923
perpustakaan_baik      0.243024
dtype: float64

#Lab Terbanyak Sekolah SMK

In [15]:
sekolahSMK = sekolah.loc[sekolah.bentuk == 'SMK']
labTerbanyakPerjenis = sekolahSMK.iloc[:,36:44].sum()
labTerbanyak = labTerbanyakPerjenis.idxmax()
print(labTerbanyakPerjenis)
print("\n\n")
print("{} adalah jumlah lab terbanyak".format(labTerbanyak))

jumlah_lab_ipa          733.0
jumlah_lab_biologi      163.0
jumlah_lab_kimia        433.0
jumlah_lab_fisika       319.0
jumlah_lab_bahasa       687.0
jumlah_lab_ips            5.0
jumlah_lab_komputer    3884.0
perpustakaan_baik      1247.0
dtype: float64



jumlah_lab_komputer adalah jumlah lab terbanyak

#Lab Terbanyak Sekolah SMA

In [18]:
sekolahSMA = sekolah.loc[sekolah.bentuk == 'SMA']
labTerbanyakPerjenis = sekolahSMA.iloc[:,36:44].sum()
labTerbanyak = labTerbanyakPerjenis.idxmax()
print(labTerbanyakPerjenis)
print("\n\n")
print("{} adalah jumlah lab terbanyak".format(labTerbanyak))

jumlah_lab_ipa         1734.0
jumlah_lab_biologi     2487.0
jumlah_lab_kimia       2324.0
jumlah_lab_fisika      2353.0
jumlah_lab_bahasa      1344.0
jumlah_lab_ips          225.0
jumlah_lab_komputer    4311.0
perpustakaan_baik      2179.0
dtype: float64



jumlah_lab_komputer adalah jumlah lab terbanyak

#Lab Terbanyak Sekolah SMP

In [19]:
sekolahSMP = sekolah.loc[sekolah.bentuk == 'SMP']
labTerbanyakPerjenis = sekolahSMP.iloc[:,36:44].sum()
labTerbanyak = labTerbanyakPerjenis.idxmax()
print(labTerbanyakPerjenis)
print("\n\n")
print("{} adalah jumlah lab terbanyak".format(labTerbanyak))

jumlah_lab_ipa         7545.0
jumlah_lab_biologi      530.0
jumlah_lab_kimia         47.0
jumlah_lab_fisika       457.0
jumlah_lab_bahasa      2062.0
jumlah_lab_ips          181.0
jumlah_lab_komputer    5318.0
perpustakaan_baik      2795.0
dtype: float64



jumlah_lab_ipa adalah jumlah lab terbanyak

#Lab Terbanyak Sekolah SD

In [20]:
sekolahSD = sekolah.loc[sekolah.bentuk == 'SD']
labTerbanyakPerjenis = sekolahSD.iloc[:,36:44].sum()
labTerbanyak = labTerbanyakPerjenis.idxmax()
print(labTerbanyakPerjenis)
print("\n\n")
print("{} adalah jumlah lab terbanyak".format(labTerbanyak))

jumlah_lab_ipa         1226.0
jumlah_lab_biologi       12.0
jumlah_lab_kimia          4.0
jumlah_lab_fisika         5.0
jumlah_lab_bahasa       263.0
jumlah_lab_ips           11.0
jumlah_lab_komputer    2922.0
perpustakaan_baik      7544.0
dtype: float64



perpustakaan_baik adalah jumlah lab terbanyak